### ISSUE TITLE
[BUG] Wrong GTFS urls for MPK Kraków

### ISSUE THREAD

**Issue by divadsn** [MobilityData/mobility-database-catalogs#140]
**Describe the bug**
https://github.com/MobilityData/mobility-database-catalogs/blob/main/catalogs/sources/gtfs/schedule/pl-malopolskie-mpk-sa-w-krakowie-gtfs-1270.json contains only GTFS data for Tram and doesn't provide direct download URL. Also, it's the ZTP Kraków authority (ztp.krakow.pl) which organizes the public transport in Kraków.

**To Reproduce**
As above.

**Expected behavior**
https://gtfs.ztp.krakow.pl/ contains everything for Busses and Trams in Kraków as seperate ZIP files.

**Screenshots**
Not needed.

**Additional context**
Not needed.

**Comment by emmambd** [comment]
Hi @divadsn! Thanks for flagging this issue. To clarify, you're suggesting the download URL for source 1270 `https://transitfeeds.com/p/mpk-sa-w-krakowie/1105/latest/download` be replaced with `https://gtfs.ztp.krakow.pl/GTFS_KRK_T.zip` and a separate source should be created for the bus URL `https://gtfs.ztp.krakow.pl/GTFS_KRK_A.zip`?

**Comment by divadsn** [comment]
@emmambd Yes exactly! 😄 

And the license url pointing to https://ztp.krakow.pl
