### ISSUE TITLE
[REQUEST] Enable flagging of a development-only dataset (not ready for public trip planning)

### ISSUE THREAD

**Issue by e-lo** [MobilityData/mobility-database-catalogs#170]
**What problem is your feature request trying to solve?**
I'd like to publicly post datasets which contain features which are under development and not ready for public trip planning and also have a central place for  data consumers to be able to find development datasets for specific features (i.e. Flex, etc.) to enable them to test their tools.

**Describe the solution you'd like**

- Extension of the schema to add a flag for development-only.  e.g. an optional field (defaults to False) where you can note: `development_only = true`
- Extension of the schema to add an enumeration of which feature(s) this feed uses.  e.g. `features = [`fares`,`flex`]
- Decision on whether/how this would interact with "publication-ready" datasets for the same feeds (i.e. different feed id? )
- An auto-summary of feeds for different features so that developers can easily find "all the datasets with fares".

**Describe alternatives you've considered**
Posting a California-only testbed summary of datasets at gtfs-dev.calitp.org

**How will we know when this is done?**
As a consumer, I can find a list of all the development feeds with various features.
As a producer, I can add development-only feeds and be confident they aren't going to be used for active trip planning.

**Comment by e-lo** [comment]
In order to get the ball rolling and people the datasets they need to start testing, I've [added a really basic PR ](https://github.com/MobilityData/mobility-database-catalogs/pull/171) to implement the above – with the major caveat that I used existing code as a template and didn't do a thorough review of the logic!

**Comment by emmambd** [comment]
Since it can easily get lost in the PR comments, I want to highlight this proposed list of features as [I originally suggested here.](https://github.com/MobilityData/mobility-database-catalogs/pull/171#issuecomment-1175486766): 

> 2. For the list of features, as a first implementation I suggest `flex-v1`, `flex-v2`, `fares-v1`, `fares-v2`, `pathways` and `occupancy`. The classifier structure would be helpful for UI (display all the sources implementing a version of “Fares”), but is not well suited for this use case (indicating that a source features “Fares” is misleading since v1 and v2 are incompatible). [Since consumers are interested in finding specific feature versions](https://mobilitydata-io.slack.com/archives/CSP7HDF37/p1656962829325989), this list seems like a good starting point. Happy to discuss further if needed.

**Comment by emmambd** [comment]
Closing this issue now that #171 has been merged.
