### ISSUE TITLE
[REQUEST] Deprecate `authentication_type=3` from RT catalog schema

### ISSUE THREAD

**Issue by lauriemerrell** [MobilityData/mobility-database-catalogs#176]
**What problem is your feature request trying to solve?**
We are planning for interoperability with the catalog, and one challenge that we have is validating URLs. Curly brace characters are not valid within URLs, so URLs with `authentication_type=3` will fail URL validation, for example through tools like [Pydantic](https://pydantic-docs.helpmanual.io/usage/types/#urls). Further, as far as we can tell, type `3` is a proper subset of type `1`, at least in the example [given in the docs](https://github.com/MobilityData/mobility-database-catalogs#gtfs-realtime-data-structure) (i.e., `https://gtfs.translink.ca/v2/gtfsalerts?apikey={API_KEY}` under type 3 would become `https://gtfs.translink.ca/v2/gtfsalerts` with `api_key_parameter_name = apikey` under type 1). In type `1`, the URLs can be parsed as valid URLs and then the authentication parameter can be added on. 

**Describe the solution you'd like**
It would be preferable for us to simply use type `1` in all cases of URL-based authentication. 

**Describe alternatives you've considered**
1. Continue using the current approach, which would require pure string manipulation of URLs, which we feel is risky and adds complexity 

**How will we know when this is done?**
1. Existing entries with `authentication_type=3` are updated to have `authentication_type=1` with URL updated accordingly (API key parameter name is moved to the relevant field, placeholder value is removed)
2. Authentication type 3 is removed from the docs & no longer supported

**Comment by emmambd** [comment]
Thanks for adding this issue @lauriemerrell! This suggestion does seem to work effectively for most cases of authentication type 3 currently in the database. 

One consideration: 

- In cases where multiple parameters must be specified, e.g `token` and `agency` in [`https://opendata.exo.quebec/ServiceGTFSR/Alert.pb?token={API_KEY}&agency=MRCLM`](https://opendata.exo.quebec/ServiceGTFSR/Alert.pb?token={API_KEY}&agency=MRCLM)

Possible solutions we see below. Please share any alternatives you see and/or preferences.

1) Keep `authentication_type=3`, but change its definition to only be for URLs with multiple required parameters so the schema can be more consistently applied. Represent the API_KEY placeholder in a different way, such as by removing the curly braces entirely and leaving `API_KEY`. The example above would then be `https://opendata.exo.quebec/ServiceGTFSR/Alert.pb?token=API_KEY&agency=MRCLM

2) Remove `authentication_type=3`. For `authentication type=1`, a URL could be listed including all the necessary parameters, except the `api_key_parameter_name`. So the example above would have a direct download URL of  `https://opendata.exo.quebec/ServiceGTFSR/Alert.pb?agency=MRCLM` and an `api_key_parameter_name` of `token`.

**Comment by lauriemerrell** [comment]
Thanks @emmambd - our preference would certainly be for #2 of the options you mentioned. That way `https://opendata.exo.quebec/ServiceGTFSR/Alert.pb?agency=MRCLM` can still be parsed as a valid URL, and using standard URL methods the authentication parameter can be added. (For example, the Python `requests` library lets you pass in a URL including some parameters and still pass in additional parameters as a dictionary in the parameters argument, and it will correctly construct the request; we have tested doing exactly that within our own GTFS pipeline to handle this case where you have auth and non-auth parameters.)

**Comment by emmambd** [comment]
@lauriemerrell Thanks for the insight! Based on this, we're going to start this week on the changes. We'll be

1. Updating all sources that currently have `authentication_type=3` to `authentication_type=1` 
2. Updating the schema so that `authentication_type=4` is removed and `authentication_type=3` is defined and used for ad-hoc authentication instead. We plan to proceed with this since it will be less confusing in the long term and realtime sources have only be available in the database for a month and a half. 

Let us know if you have any additional feedback.
