### ISSUE TITLE
Upgrade Fiona

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-database-catalogs#266]
**Describe the bug**
There's currently an error when installing Fiona as a dependency when using newer versions of Python.

```
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Fiona
```

**Solution** 
Upgrade Fiona to https://pypi.org/project/Fiona/1.9.1/

**Comment by davidgamez** [comment]
Fixed by #524
