### ISSUE TITLE
Passenger sources

### ISSUE THREAD

**Issue by Cj-Malone** [MobilityData/mobility-database-catalogs#289]
Hello, I don't quite know how this works, but I'd like to request some sources added.

[Passenger](https://data.discoverpassenger.com/) do the tech for a bunch of providers in the UK, they publish GTFS files for some of the, eg https://data.discoverpassenger.com/operator/bts.

Could they be added please.

**Comment by emmambd** [comment]
Hi @Cj-Malone! Thanks for flagging this and sharing these feeds with the community 🎉. I can add the Blackpool Transport GTFS feed. 

Others you'd like to add can be submitted in 1 of 2 ways, depending on your comfort with Github: 

-  [Our form](https://database.mobilitydata.org/update-a-data-source) here
- Following the contribution process for [adding JSON files here](https://github.com/MobilityData/mobility-database-catalogs/blob/main/CONTRIBUTING.md).

**Comment by Cj-Malone** [comment]
I couldn't workout how to generate the json files myself so I filled out the Google form, Thank you.
