### ISSUE TITLE
[BUG] Fixing frequent Python errors when using operations.

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-database-catalogs#323]
**Describe the bug**
I get the following recurring bugs when I follow the steps in [Installation](https://github.com/MobilityData/mobility-database-catalogs?tab=readme-ov-file#installation) and [Adding feeds](https://github.com/MobilityData/mobility-database-catalogs/blob/main/CONTRIBUTING.md#data-contribution-flow)

**To Reproduce**
1. Use internal Linux virtual machine (MobilityData specific step)
2. Follow [Installation instructions](https://github.com/MobilityData/mobility-database-catalogs?tab=readme-ov-file#installation) up to and including `source env/bin/activate`
3. Run `from tools.operations import *`
4. Get: `ModuleNotFoundError: No module named 'gtfs_kit'`

If I rerun the `pip install -r requirements.txt` command outside the Python VM, then rerun `from tools.operations import *` I get a new error: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte`

**Expected behavior**
No error returned after `from tools.operations import *`

**Comment by a-albashir** [comment]
Hello,
I was countering the same issue but it seems changing the opening statement in the `tools/representations.py` solved the problem.

Specifically, you can replace the line 91 in that script  which now is 
`with open(os.path.join(path, file)) as fp:` 
To
`with open(os.path.join(path, file), encoding='utf-8') as fp:`
This solved the problem for me as it avoiding the `UnicodeDecodeError` by indicate the correct encoding format.

**Comment by emmambd** [comment]
@a-albashir Thank you for troubleshooting this and suggesting this modification! 

Would it be possible for you to contribute this fix as a PR so the community can benefit?

**Comment by davidgamez** [comment]
Fixed by #524
