### ISSUE TITLE
GTFS feed change following new website deployment

### ISSUE THREAD

**Issue by rcoulombe** [MobilityData/mobility-database-catalogs#350]
Hi,

Following a new website deployment, the GTFS feed for STO (Gatineau) has been changed. It would be necessary to update the feed. 

The new feed is https://contenu.sto.ca/GTFS/GTFS.zip

The primary change is that the address is nos HTTPS instead of HTTP.

Could you please update the feed?

Thank you!

**Comment by emmambd** [comment]
@rcoulombe Thanks for flagging this change! We will update the URL in our next round of feed updates.
