### ISSUE TITLE
Investigate how often we should be pulling new feed versions

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-database-catalogs#375]
**What problem is your feature request trying to solve?**
It looks like feeds are updating more regularly than the once a week cadence we have on the Mobility Database API. We can run analytics on the daily updated feeds we have in the catalogs repo to see how frequently it would make sense to update.

**Comment by davidgamez** [comment]
Tasks:
 - [ ] Create a script to gather information on how often feeds are updated. Use current catalog file hastag
 - [ ] Share with the teams

**Comment by cka-y** [comment]
## Findings on Optimal Update Frequency for GTFS Feeds

After running the script for 23 days using the feed MD5 hash to determine dataset updates, we analyzed the frequency of feed changes. The goal was to assess how often we should check for updates beyond the current weekly cadence on the Mobility Database API. To ensure the data is not skewed by invalid feeds, we filtered out feeds identified as invalid based on findings from https://github.com/MobilityData/mobility-feed-api/pull/501. Below is a graph comparing results for all feeds versus only valid feeds (i.e., feeds known to have returned a valid dataset at some point).

![Image](https://github.com/MobilityData/mobility-database-catalogs/assets/60586858/c3a7be61-7a47-4091-9916-ffefc4f0e8b1)

The difference between all feeds and only valid feeds is minimal, making it hard to discern differences at 100% zoom. Therefore, tendencies are similar across both categories. Here is a detailed table summarizing the cumulative percentage of changes captured for each update frequency:

| Days Between Updates | % of Changes Captured |
|----------------------|-----------------------|
| 1                    | 100.00%               |
| 2                    | 26.95%                |
| 3                    | 18.66%                |
| 4                    | 13.40%                |
| 5                    | 11.75%                |
| 6                    | 10.62%                |
| 7                    | 9.17%                 |
| 8                    | 6.91%                 |
| 9                    | 6.10%                 |
| 10                   | 5.42%                 |
| 11                   | 4.62%                 |
| 12                   | 4.10%                 |
| 13                   | 3.84%                 |
| 14                   | 3.32%                 |
| 15                   | 2.65%                 |
| 16                   | 2.13%                 |
| 17                   | 1.87%                 |
| 18                   | 1.42%                 |
| 19                   | 1.23%                 |
| 20                   | 1.07%                 |
| 21                   | 0.52%                 |
| 22                   | 0.29%                 |
| 23                   | 0.26%                 |

We observe that moving from daily updates to checking every two days results in missing almost 3/4 of all feed changes.

### Conclusion

To maximize the capture of feed changes, it is advisable to check for updates daily if capacity allows. However, if there is a need to reduce costs, a frequency of every three days could be a viable compromise, although this would still miss a significant portion of updates.

**Comment by emmambd** [comment]
@cka-y Do we need an issue to act on the findings here?
