### ISSUE TITLE
[REQUEST] Add Southern Moravia data feed

### ISSUE THREAD

**Issue by mcepl** [MobilityData/mobility-database-catalogs#385]
There is this GTFS feed for traffic data in IDS JMK (Integrated Transportation System of the Southern Moravia Region, Czechia). Could you add it?

https://data.brno.cz/datasets/379d2e9a7907460c8ca7fda1f3e84328/about

**Comment by emmambd** [comment]
Thanks for sharing this @mcepl! We'll add it to our issue tracker to add.

**Comment by kudlav** [comment]
Added in https://github.com/MobilityData/mobility-database-catalogs/pull/557
I hope this Issue can be closed.

**Comment by emmambd** [comment]
Thanks for pointing this out @kudlav! You're right, this issue can be closed.
