### ISSUE TITLE
NEW FEED ADDED : Daytrip Shuttle

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/mobility-database-catalogs#405]
# Daytrip Shuttle
#### Data type
GTFS Schedule ("static")
#### Issue type
New feed
#### Your name and organization
Daytrip

## URLs
| Current URL on OpenMobilityData.org | Updated/new feed URL | Download URL | Link to dataset |
|---|---|---|---|
|  | https://gtfs.daytrip.com/gtfs_pt.zip | n/a |  |

## View more details
https://docs.google.com/spreadsheets/d/1Q96KDppKsn2khdrkraZCQ7T_qRSfwj7WsvqXvuMt4Bc

**Comment by emmambd** [comment]
Duplicate
