### ISSUE TITLE
NEW FEED ADDED : C-TRAN

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/mobility-database-catalogs#407]
# C-TRAN
#### Data type
GTFS Realtime - Vehicle Positions
#### Issue type
New source
#### Your name and organization
Taylor Eidt (C-TRAN)

## URLs
| Current URL on OpenMobilityData.org | Updated/new feed URL | Download URL | Link to dataset |
|---|---|---|---|
|  |  | http://gtfs-rt.c-tran.org/gtfsrealtime/VehiclePostions | https://www.c-tran.com/about-c-tran/business/c-tran-gtfs-data |

## View more details
https://docs.google.com/spreadsheets/d/1Q96KDppKsn2khdrkraZCQ7T_qRSfwj7WsvqXvuMt4Bc

**Comment by emmambd** [comment]
Already present in the Mobility Database - bug that it was added
