### ISSUE TITLE
Create a PR automatically when the import Github Action is run 

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-database-catalogs#457]
**What problem is your feature request trying to solve?**
Right now after the Github action is run, we have to 

- Go to the new branch
- Create a new PR

**Describe the solution you'd like**
Would be more convenient if a PR is just automatically created upon running the Github action.

**How will we know when this is done?**
A PR is automatically generated when the Github action runs

**Comment by fredericsimard** [comment]
@emmambd I think so. Should be done by Monday.

**Comment by fredericsimard** [comment]
Closed by #477
