### ISSUE TITLE
[REQUEST] Add BurbankBus feed

### ISSUE THREAD

**Issue by michaelkirk** [MobilityData/mobility-database-catalogs#505]
Sorry if this isn't the right way to go about this — I wanted to add a feed for Burbank Bus: https://www.burbankca.gov/burbankbus

I was going to go through the form submission process to submit a new feed, but per #504, the submission form seems down.

gtfs feed: https://rideburbankbus.com/gtfs
bbox: -118.376084 34.138421 -118.311824 34.19569496664857

I can try again after #504 is resolved, or I'd be happy if someone else wanted to submit it.

**Comment by emmambd** [comment]
Thanks @michaelkirk for this submission! Burbank Bus has now been added.
