### ISSUE TITLE
[BUG] It seems 860 is obsolete and it has been replaced by 767

### ISSUE THREAD

**Issue by mcepl** [MobilityData/mobility-database-catalogs#553]
**Describe the bug**
When analysing the situation with the public transportation in Prague, we found that the feed 860 is probably out-of-date and Prague users should use 767 instead.

[Original source](https://opendata.praha.eu/datasets/https%3A%2F%2Fapi.opendata.praha.eu%2Flod%2Fcatalog%2F9a6a1d8e-45b9-41de-b9ae-0bcec7126876).

**Comment by emmambd** [comment]
@mcepl Thanks for sharing this! We've reviewed the feeds and updated this to point to 767 as the up-to-date source.
