### ISSUE TITLE
New Feed Added: IDS JMK

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/mobility-database-catalogs#556]
# Agency name/Transit Provider: 

  ### Location
  CZ, South Moravian

  ## Details

  #### Data type
  gtfs

  #### Issue type
  New feed

  ## URLs
  | Current URL on OpenMobilityData.org | Updated/new feed URL |
  |---|---|
  |  | https://www.arcgis.com/sharing/rest/content/items/379d2e9a7907460c8ca7fda1f3e84328/data |

  ## Authentication
  #### Authentication type
  None - 0

  ## View more details
  https://docs.google.com/spreadsheets/d/10eIUxWVtLmc2EATiwivgXBf4bOMErOnq7GFIoRedXHU/edit

**Comment by kudlav** [comment]
GTFS Realtime: https://content.idsjmk.cz/kestazeni/gtfsReal.dat
