### ISSUE TITLE
Elevated Transit shut down in 2017 but it is not marked deprecated

### ISSUE THREAD

**Issue by dancory-urbanfootprint** [MobilityData/mobility-database-catalogs#561]
Elevated Transit https://mobilitydatabase.org/feeds/mdb-1207 shut down in 2017 according to https://en.wikipedia.org/wiki/Elevated_Transit

In the spreadsheet at https://bit.ly/catalogs-csv, it is marked as inactive but not deprecated

**Comment by emmambd** [comment]
Fixed in #567
