### ISSUE TITLE
New Feed Added: City of Milton-Freewater Public Transportation

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/mobility-database-catalogs#563]
# Agency name/Transit Provider: 

  ### Location
  US, Oregon, Milton-Freewater

  ## Details

  #### Data type
  gtfs

  #### Issue type
  Feed update

  ## URLs
  | Current URL on OpenMobilityData.org | Updated/new feed URL |
  |---|---|
  | http://oregon-gtfs.com/gtfs_data/milton-freewater-or-us/milton-freewater-or-us.zip | https://oregon-gtfs.trilliumtransit.com/gtfs_data/ctuir-or-us/ctuir-or-us.zip |

  ## Authentication
  #### Authentication type
  None - 0

  ## View more details
  https://docs.google.com/spreadsheets/d/10eIUxWVtLmc2EATiwivgXBf4bOMErOnq7GFIoRedXHU/edit

**Comment by emmambd** [comment]
Closed in #567
