### ISSUE TITLE
New Feed Added: Empresa Malagueña de Transportes - Official Feed

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/mobility-database-catalogs#572]
# Agency name/Transit Provider: EMT Málaga

  ### Location
  ES, Andalucía, Málaga

  ## Details

  #### Data type
  gtfs

  #### Issue type
  Feed update

  #### Name
  EMT Málaga

  ## URLs
  | Current URL on OpenMobilityData.org | Updated/new feed URL |
  |---|---|
  | https://mobilitydatabase.org/feeds/mdb-1113 | https://gtfs.emtmalaga.es/GTFS/google_transit.zip |

  ## Authentication
  #### Authentication type
  None - 0

  ## View more details
  https://docs.google.com/spreadsheets/d/10eIUxWVtLmc2EATiwivgXBf4bOMErOnq7GFIoRedXHU/edit

**Comment by emmambd** [comment]
Closed in #586
