### ISSUE TITLE
New Feed Added: Empresa Malagueña de Transportes - Official Feed

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/mobility-database-catalogs#573]
# Agency name/Transit Provider: 

  ## Details

  #### Data type
  gtfs_rt

  #### Issue type
  New feed

  ## URLs
  | Current URL on OpenMobilityData.org | Updated/new feed URL |
  |---|---|
  |  | https://gtfs.emtmalaga.es/GTFSRTapi/api/tripupdate |
  |  | https://gtfs.emtmalaga.es/GTFSRTapi/api/vehicleposition |
  |  | http://gtfs.emtmalaga.es/GTFSRTapi/api/alert |

  ## Authentication
  #### Authentication type
  None - 0

  ## View more details
  https://docs.google.com/spreadsheets/d/10eIUxWVtLmc2EATiwivgXBf4bOMErOnq7GFIoRedXHU/edit

**Comment by emmambd** [comment]
Closed in #586
