### ISSUE TITLE
New Feed Added: Froggy Transportation - Official Feed

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/mobility-database-catalogs#579]
# Agency name/Transit Provider: 

  ### Location
  US, Ohio, Toledo

  ## Details

  #### Data type
  gtfs

  #### Issue type
  New feed

  ## URLs
  | Current URL on OpenMobilityData.org | Updated/new feed URL |
  |---|---|
  |  | https://rapid.nationalrtap.org/GTFSFileManagement/UserUploadFiles/11830/T.zip |

  ## Authentication
  #### Authentication type
  None - 0

  ## View more details
  https://docs.google.com/spreadsheets/d/10eIUxWVtLmc2EATiwivgXBf4bOMErOnq7GFIoRedXHU/edit

**Comment by emmambd** [comment]
Closed in #586
