### ISSUE TITLE
New Feed Added: Madison Metro - Official Feed

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/mobility-database-catalogs#580]
# Agency name/Transit Provider: Madison Metro

  ### Location
  US, Wisconsin, Madison

  ## Details

  #### Data type
  gtfs

  #### Issue type
  New feed

  #### Name
  Madison Metro

  ## URLs
  | Current URL on OpenMobilityData.org | Updated/new feed URL |
  |---|---|
  |  | http://transitdata.cityofmadison.com/GTFS/ |

  ## Authentication
  #### Authentication type
  None - 0

  ## View more details
  https://docs.google.com/spreadsheets/d/10eIUxWVtLmc2EATiwivgXBf4bOMErOnq7GFIoRedXHU/edit

**Comment by emmambd** [comment]
Already on the Mobility Database: https://mobilitydatabase.org/feeds/mdb-394
