### ISSUE TITLE
New Feed Added: Madison Metro - Official Feed

### ISSUE THREAD

**Issue by mobilitydataio** [MobilityData/mobility-database-catalogs#581]
# Agency name/Transit Provider: 

  ## Details

  #### Data type
  gtfs_rt

  #### Issue type
  New feed

  ## URLs
  | Current URL on OpenMobilityData.org | Updated/new feed URL |
  |---|---|
  |  | https://metromap.cityofmadison.com/gtfsrt/trips |
  |  | https://metromap.cityofmadison.com/gtfsrt/vehicles |
  |  | https://metromap.cityofmadison.com/gtfsrt/alerts |

  ## Authentication
  #### Authentication type
  None - 0

  ## View more details
  https://docs.google.com/spreadsheets/d/10eIUxWVtLmc2EATiwivgXBf4bOMErOnq7GFIoRedXHU/edit

**Comment by emmambd** [comment]
Closed in #586
