### ISSUE TITLE
Changing auto-discovery URL to direct download URL

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-database-catalogs#62]
**What problem are we trying to solve?**
We want to change the auto-discovery URL because "discovery" is not a commonly used term or convention in GTFS. (The original term was inspired by GBFS' systems.csv). 

We intend to change this to "direct download URL" so it's clear that this link downloads a source.

**How will we know when this is done?**

All references to auto-discovery URL removed in the JSON schema, operations, and CSV export, and direct download URL used instead.

**Comment by e-lo** [comment]
I like the consolidation to a single URL to find the data - wondering if should just be `URL`? and then the description could be "URL which downloads the data".

**Comment by maximearmstrong** [comment]
@e-lo I saw your comment after merging the PR yesterday. The `direct_download` is nested under `urls`. We now have `{"urls": {"direct_download": "...", "latest": "...", "license": "..."}}`. Do you think that using `URL` instead of `direct_download` would be better in that context?
